columns:
  title:
    type: text
    options:
      label: admin.news.list.title.label
      editable: true
  date:
    type: datetime
    options:
      label: admin.news.list.date.label
      editable: true
      input_type: datetime
  actions:
    type: action
    options:
      label: admin.news.list.actions.label
      field_mapping: ['id']
      actions:
        edit:
          route_name: fsi_admin_crud_edit
          additional_parameters: {'element' : 'news'}
          parameters_field_mapping: {'id' : 'id'}