language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhmv

before_install:
    - sudo apt-get update > /dev/null
    
matrix:
    allow_failures:
        php: hhmv
    
script:
    - composer self-update
    - composer update -n --prefer-source
    - ./bin/phpspec run -f pretty
    - ./bin/behat --no-snippets --no-paths --verbose --format=progress